--------------------------------------------------------
--  文件已创建 - 星期二-十二月-31-2019   
--------------------------------------------------------
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_DATA_GROUP 正在尝试内部生成器。
CREATE TABLE SYS_DATA_GROUP 
(
  ID NUMBER(*, 0) NOT NULL 
, DESCRIPTION VARCHAR2(256 BYTE) 
, PARENT_ID NUMBER(*, 0) 
, NAME VARCHAR2(256 BYTE) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME DATE 
, UPDATE_TIME DATE 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_DATA_ITEM 正在尝试内部生成器。
CREATE TABLE SYS_DATA_ITEM 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_DATA_GROUP_ID NUMBER(*, 0) 
, KEY_VALUE VARCHAR2(256 BYTE) 
, KEY_NAME VARCHAR2(256 BYTE) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, DESCRIPTION VARCHAR2(256 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_IP_FORBIDDEN 正在尝试内部生成器。
CREATE TABLE SYS_IP_FORBIDDEN 
(
  ID NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) DEFAULT 0 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) DEFAULT 1 
, EXPIRE_TIME TIMESTAMP(6) 
, DESCRIPTION VARCHAR2(256 BYTE) 
, IP VARCHAR2(256 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_LOG 正在尝试内部生成器。
CREATE TABLE SYS_LOG 
(
  ID NUMBER(*, 0) NOT NULL 
, RANK NUMBER(*, 0) DEFAULT 0 
, CREATE_TIME DATE 
, UPDATE_TIME DATE 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) DEFAULT 1 
, IP VARCHAR2(50 BYTE) 
, USER_ID VARCHAR2(256 BYTE) 
, METHOD VARCHAR2(256 BYTE) 
, PARAM CLOB 
, RESULT CLOB 
, DURATION NUMBER(*, 0) 
, URL VARCHAR2(256 BYTE) 
, USER_AGENT VARCHAR2(256 BYTE) 
, MODULE_NAME VARCHAR2(50 BYTE) 
, EVENT_TYPE VARCHAR2(50 BYTE) 
, LOG_TYPE VARCHAR2(50 BYTE) 
, USER_NAME VARCHAR2(50 BYTE) 
, REMARK VARCHAR2(200 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL 
LOB (PARAM) STORE AS SYS_LOB0000075663C00011$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
) 	
LOB (RESULT) STORE AS SYS_LOB0000075663C00012$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  PCTVERSION 10 
  NOCACHE 
  LOGGING 
  TABLESPACE USERS 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS UNLIMITED 
    BUFFER_POOL DEFAULT 
  )  
)COMMENT ON COLUMN SYS_LOG.MODULE_NAME IS '模块名';
COMMENT ON COLUMN SYS_LOG.EVENT_TYPE IS '事件类型';
COMMENT ON COLUMN SYS_LOG.LOG_TYPE IS '日志类型';
COMMENT ON COLUMN SYS_LOG.USER_NAME IS '用户名';
COMMENT ON COLUMN SYS_LOG.REMARK IS '描述';
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_LOGIN_STATUS 正在尝试内部生成器。
CREATE TABLE SYS_LOGIN_STATUS 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_USER_ID NUMBER(*, 0) 
, SESSION_ID VARCHAR2(256 BYTE) 
, SESSION_EXPIRES TIMESTAMP(6) 
, SYS_USER_LOGIN_NAME VARCHAR2(256 BYTE) 
, SYS_USER_ZH_NAME VARCHAR2(256 BYTE) 
, LAST_LOGIN_TIME TIMESTAMP(6) 
, PLATFORM NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) DEFAULT 1 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_LOGINLOG 正在尝试内部生成器。
CREATE TABLE SYS_LOGINLOG 
(
  ACCOUNT VARCHAR2(50 BYTE) 
, ID NUMBER(*, 0) NOT NULL 
, ADDTIME TIMESTAMP(6) 
, UPDATETIME TIMESTAMP(6) 
, LOGINIP VARCHAR2(50 BYTE) 
, LOGINTIME TIMESTAMP(6) 
, ISSUCCESS CHAR(1 BYTE) 
, ERRORMSG VARCHAR2(100 BYTE) 
, LOGTYPE VARCHAR2(10 BYTE) 
, MODULE_NAME VARCHAR2(50 BYTE) 
, EVENT_TYPE VARCHAR2(50 BYTE) 
, LOG_TYPE VARCHAR2(50 BYTE) 
, USER_NAME VARCHAR2(50 BYTE) 
, REMARK VARCHAR2(200 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCOMMENT ON COLUMN SYS_LOGINLOG.MODULE_NAME IS '模块类型';
COMMENT ON COLUMN SYS_LOGINLOG.EVENT_TYPE IS '事件类型';
COMMENT ON COLUMN SYS_LOGINLOG.LOG_TYPE IS '日志类型';
COMMENT ON COLUMN SYS_LOGINLOG.USER_NAME IS '用户名称';
COMMENT ON COLUMN SYS_LOGINLOG.REMARK IS '描述';
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_LOGINRECORDS 正在尝试内部生成器。
CREATE TABLE SYS_LOGINRECORDS 
(
  ID NUMBER(*, 0) NOT NULL 
, LASTLOGINIP VARCHAR2(36 BYTE) 
, LOGINCOUNT NUMBER(*, 0) 
, LASTLOGINTIME TIMESTAMP(6) 
, ACCOUNT VARCHAR2(50 BYTE) 
, ADDTIME TIMESTAMP(6) 
, UPDATETIME TIMESTAMP(6) 
, LOGINIP VARCHAR2(50 BYTE) 
, LOGINTIME TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_ORGANIZATION 正在尝试内部生成器。
CREATE TABLE SYS_ORGANIZATION 
(
  ID NUMBER(*, 0) NOT NULL 
, NAME VARCHAR2(256 BYTE) 
, DESCRIPTION VARCHAR2(256 BYTE) 
, IS_FINAL NUMBER(*, 0) 
, PARENT_ID NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, FULL_NAME VARCHAR2(256 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_PERMISSION 正在尝试内部生成器。
CREATE TABLE SYS_PERMISSION 
(
  ID NUMBER(*, 0) NOT NULL 
, NAME VARCHAR2(256 BYTE) 
, DESCRIPTION VARCHAR2(256 BYTE) 
, CODE VARCHAR2(256 BYTE) 
, SYS_PERMISSION_GROUP_ID NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) DEFAULT 1 
, REQUEST_URL VARCHAR2(500 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_PERMISSION_GROUP 正在尝试内部生成器。
CREATE TABLE SYS_PERMISSION_GROUP 
(
  ID NUMBER(*, 0) NOT NULL 
, NAME VARCHAR2(256 BYTE) 
, DESCRIPTION VARCHAR2(256 BYTE) 
, PARENT_ID NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, MENU_CODE VARCHAR2(50 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_ROLE 正在尝试内部生成器。
CREATE TABLE SYS_ROLE 
(
  ID NUMBER(*, 0) NOT NULL 
, DESCRIPTION VARCHAR2(256 BYTE) 
, NAME VARCHAR2(256 BYTE) 
, RANK NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) DEFAULT 0 
, UPDATE_BY NUMBER(*, 0) DEFAULT 0 
, STATUS NUMBER(*, 0) DEFAULT 1 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_ROLE_MENU 正在尝试内部生成器。
CREATE TABLE SYS_ROLE_MENU 
(
  ID VARCHAR2(20 BYTE) NOT NULL 
, ROLE_ID NUMBER(*, 0) 
, MENU_ID NUMBER(*, 0) 
, MENU_STATE NUMBER(*, 0) 
, MENU_CREATE_DATE VARCHAR2(20 BYTE) 
, MENU_UPDATA_DATE VARCHAR2(20 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_ROLE_ORGANIZATION 正在尝试内部生成器。
CREATE TABLE SYS_ROLE_ORGANIZATION 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_ORGANIZATION_ID NUMBER(*, 0) 
, SYS_ROLE_ID NUMBER(*, 0) 
, PARENT_ID NUMBER(*, 0) 
, NAME VARCHAR2(256 BYTE) 
, FULL_NAME VARCHAR2(256 BYTE) 
, DESCRIPTION VARCHAR2(256 BYTE) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_ROLE_PERMISSION 正在尝试内部生成器。
CREATE TABLE SYS_ROLE_PERMISSION 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_PERMISSION_ID NUMBER(*, 0) 
, SYS_ROLE_ID NUMBER(*, 0) 
, RANK NUMBER(*, 0) DEFAULT 0 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) DEFAULT 0 
, UPDATE_BY NUMBER(*, 0) DEFAULT 0 
, STATUS NUMBER(*, 0) DEFAULT 1 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_SYSTEMSETTING 正在尝试内部生成器。
CREATE TABLE SYS_SYSTEMSETTING 
(
  VISITSTARTTIME TIMESTAMP(6) 
, VISITENDTIME TIMESTAMP(6) 
, IPLIST VARCHAR2(2000 BYTE) 
, TXTEMAILADDR VARCHAR2(256 BYTE) 
, TXTEMAILPORT VARCHAR2(256 BYTE) 
, TXTEMAILUSERNAME VARCHAR2(50 BYTE) 
, TXTEMAILPWD VARCHAR2(50 BYTE) 
, TXTLOGINFALSECOUNT NUMBER(*, 0) 
, TXTLOGINLOCKTIME NUMBER(*, 0) 
, TXTEDITPWDTIME NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, RANK VARCHAR2(50 BYTE) 
, TXTSESSIONMAXTIME NUMBER(38, 0) 
, TXTSESSIONMAXCOUNT NUMBER(38, 0) 
, SYS_SYSTEMSETTING_ID VARCHAR2(36 BYTE) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_USER 正在尝试内部生成器。
CREATE TABLE SYS_USER 
(
  ID NUMBER(*, 0) NOT NULL 
, LOGIN_NAME VARCHAR2(256 BYTE) 
, ZH_NAME VARCHAR2(256 BYTE) 
, EN_NAME VARCHAR2(256 BYTE) 
, SEX NUMBER(*, 0) 
, BIRTH VARCHAR2(50 BYTE) 
, EMAIL VARCHAR2(100 BYTE) 
, PHONE VARCHAR2(50 BYTE) 
, ADDRESS VARCHAR2(256 BYTE) 
, PASSWORD VARCHAR2(250 BYTE) 
, PASSWORD_SALT VARCHAR2(256 BYTE) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, EXPIRY_TIME TIMESTAMP(6) 
, PASSWORD_UPDATE_TIME TIMESTAMP(6) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_USER_PERMISSION 正在尝试内部生成器。
CREATE TABLE SYS_USER_PERMISSION 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_USER_ID NUMBER(*, 0) 
, SYS_PERMISSION_ID NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_USER_ROLE 正在尝试内部生成器。
CREATE TABLE SYS_USER_ROLE 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_USER_ID NUMBER(*, 0) 
, SYS_ROLE_ID NUMBER(*, 0) 
, RANK NUMBER(*, 0) DEFAULT 0 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) DEFAULT 0 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) DEFAULT 1 
, IS_FINAL NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
-- 无法呈现对象 ADMINSYSTEM 的 TABLE DDL。带有 DBMS_METADATA 的 SYS_USER_ROLE_ORGANIZATION 正在尝试内部生成器。
CREATE TABLE SYS_USER_ROLE_ORGANIZATION 
(
  ID NUMBER(*, 0) NOT NULL 
, SYS_USER_ID NUMBER(*, 0) 
, SYS_ROLE_ORGANIZATION_ID NUMBER(*, 0) 
, RANK NUMBER(*, 0) 
, CREATE_TIME TIMESTAMP(6) 
, UPDATE_TIME TIMESTAMP(6) 
, CREATE_BY NUMBER(*, 0) 
, UPDATE_BY NUMBER(*, 0) 
, STATUS NUMBER(*, 0) 
, IS_FINAL NUMBER(*, 0) 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL
